# Generated by Django 5.2.17 on 2026-08-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_knowledgearticle_tickettag_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('manage_workflow', 'Can manage ticket workflow'), ('delete_chats', 'Can delete complete chats'), ('view_audit_log', 'Can view the audit log'), ('manage_knowledge', 'Can manage knowledge articles')]},
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
