from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from . import enhancements

urlpatterns = [
    path("", views.ticket_list, name="ticket_list"),
    path("create/", views.ticket_create, name="ticket_create"),
    path("account/", views.account_update, name="account_update"),
    path("login/", views.login_view, name="login"),
    path("two-factor/", views.two_factor_verify, name="two_factor_verify"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="tickets/password_reset.html", email_template_name="tickets/password_reset_email.txt", success_url="done/"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="tickets/password_reset_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="tickets/password_reset_confirm.html", success_url="complete/"), name="password_reset_confirm"),
    path("reset/<uidb64>/<token>/complete/", auth_views.PasswordResetCompleteView.as_view(template_name="tickets/password_reset_complete.html"), name="password_reset_complete"),
    path("<int:ticket_id>/messages/", views.ticket_messages, name="ticket_messages"),
    path("<int:ticket_id>/chat/", views.ticket_chat_delete, name="ticket_chat_delete"),
    path("<int:ticket_id>/chat/archive/", views.ticket_chat_archive, name="ticket_chat_archive"),
    path("<int:ticket_id>/status/", views.ticket_status, name="ticket_status"),
    path("status/bulk/", views.ticket_bulk_status, name="ticket_bulk_status"),
    path("<int:ticket_id>/assign/", views.ticket_assign, name="ticket_assign"),
    path("portal/", views.customer_portal, name="customer_portal"),
    path("platform/", views.platform_admin, name="platform_admin"),
    path("platform/access/", views.platform_access, name="platform_access"),
    path("platform/users/create/", views.platform_user_create, name="platform_user_create"),
    path("platform/users/<int:user_id>/", views.platform_user_update, name="platform_user_update"),
    path("direct/users/", views.direct_message_users, name="direct_message_users"),
    path("direct/<int:user_id>/", views.direct_message_thread, name="direct_message_thread"),
    path("direct/<int:user_id>/chat/", views.direct_chat_delete, name="direct_chat_delete"),
    path("direct/<int:user_id>/chat/archive/", views.direct_chat_archive, name="direct_chat_archive"),
    path("<int:ticket_id>/notes/", enhancements.ticket_notes, name="ticket_notes"),
    path("<int:ticket_id>/presence/", enhancements.ticket_presence, name="ticket_presence"),
    path("<int:ticket_id>/reopen/", enhancements.reopen_ticket, name="reopen_ticket"),
    path("<int:ticket_id>/rate/", enhancements.rate_ticket, name="rate_ticket"),
    path("saved-views/", enhancements.saved_views, name="saved_views"),
    path("canned-replies/", enhancements.canned_replies, name="canned_replies"),
    path("notifications/", enhancements.notifications, name="notifications"),
    path("knowledge/search/", enhancements.knowledge_search, name="knowledge_search"),
    path("<int:ticket_id>/attachments/", enhancements.ticket_attachment, name="ticket_attachment"),
    path("preferences/", enhancements.preferences, name="preferences"),
    path("audit/", enhancements.audit_log, name="audit_log"),
    path("two-factor/settings/", enhancements.two_factor_settings, name="two_factor_settings"),
    path("platform/users/<int:user_id>/sessions/revoke/", enhancements.revoke_user_sessions, name="revoke_user_sessions"),
    path("verify-email/send/", enhancements.send_verification, name="send_verification"),
    path("verify-email/<str:token>/", enhancements.verify_email, name="verify_email"),
    path("<int:ticket_id>/workflow/", enhancements.ticket_workflow, name="ticket_workflow"),
    path("<int:ticket_id>/merge/", enhancements.merge_ticket, name="merge_ticket"),
    path("agents/workload/", enhancements.agent_workload, name="agent_workload"),
]
